info.project.name=Employee Management
info.project.instructor= Avej
info.project.env=local
server.port = 8090
#Enabling H2 CONSOLE
#
#spring.h2.console.enabled=True
#spring.h2.console.path=/h2
#spring.datasource.url=jdbc:h2:mem:EmployeeDB
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=1234


spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeDB
spring.datasource.username=root
spring.datasource.password=Avej@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name=Avej
#spring.security.user.password=1234

spring.thymeleaf.enabled=true



